import type { Config } from "tailwindcss";

// Colors + type scale copied verbatim from the "Precision Infrastructure System" DESIGN.md
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#390c00",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "tertiary-fixed": "#ffdbd0",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c6d8",
        primary: "#0050cb",
        "tertiary-container": "#cc4204",
        background: "#faf8ff",
        "on-secondary-fixed": "#0b1c30",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        tertiary: "#a33200",
        "inverse-surface": "#283044",
        outline: "#727687",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "secondary-container": "#d0e1fb",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "surface-tint": "#0054d6",
        "primary-fixed": "#dae1ff",
        surface: "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#424656",
        "on-tertiary-container": "#fff6f4",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#001849",
        "primary-container": "#0066ff",
        "on-primary-container": "#f8f7ff",
        secondary: "#505f76",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#b3c5ff",
        "on-secondary-container": "#54647a",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-fixed-variant": "#832600",
        // dark-mode anchors from DESIGN.md
        "dark-surface": "#1a2133",
        "dark-log": "#0b101e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "8px",
        "container-padding": "16px",
        unit: "4px",
        "row-height-sm": "32px",
        "row-height-md": "40px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        h1: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-xs": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        code: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
